// Command sbom-submit posts an SBOM file to a running devradar-serve instance.
// It reads the file and base64-encodes it into the JSON body, avoiding the shell
// ARG_MAX limit you hit passing a multi-MB SBOM to `curl -d` directly. This is
// the simplest submission path for CI and local use alike.
//
// Usage:
//
//	export DR_TOKEN=dr_...            # from 'make seed' (local) or the UI (prod)
//	export DR_BASE_URL=https://devradar.thingz.io   # defaults to localhost:8080
//	go run ./tools/sbom-submit <sbom-file> [image_ref@sha256:...]
//
// The optional second argument is an image_ref override, needed when the SBOM
// was generated by tag (generators embed only layer digests then, not the image
// manifest digest). Prefer generating SBOMs by digest — see the README.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
)

func main() {
	if len(os.Args) < 2 {
		log.Fatal("usage: sbom-submit <sbom-file> [image_ref@sha256:...]")
	}
	token := os.Getenv("DR_TOKEN")
	if token == "" {
		log.Fatal("set DR_TOKEN (see 'make seed')")
	}
	base := os.Getenv("DR_BASE_URL")
	if base == "" {
		base = "http://localhost:8080"
	}

	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		log.Fatalf("read sbom: %v", err)
	}
	payload := map[string]string{"sbom": base64.StdEncoding.EncodeToString(raw)}
	if len(os.Args) > 2 && os.Args[2] != "" {
		payload["image_ref"] = os.Args[2]
	}
	body, _ := json.Marshal(payload)

	req, err := http.NewRequest(http.MethodPost, base+"/v1/sboms", bytes.NewReader(body))
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatalf("submit: %v", err)
	}
	out, _ := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	fmt.Printf("HTTP %d: %s\n", resp.StatusCode, out)
	if resp.StatusCode >= 300 {
		os.Exit(1)
	}
}
