// Command sbom-submit submits an SBOM to a devradar-serve instance.
//
// It works in two modes, chosen by the argument:
//
//   - Image mode (the common case): given an image reference, it resolves the
//     manifest digest with `crane`, generates an all-layers CycloneDX SBOM with
//     `syft` against the digest-pinned reference, and submits it. This hides the
//     by-digest / all-layers / base64 details the README spells out.
//
//     go run ./tools/sbom-submit quay.io/jetstack/cert-manager-cainjector:v1.20.2
//
//   - File mode: given a path to an existing SBOM file, it submits that file
//     as-is. An optional second argument is an `image_ref` override
//     (`repo@sha256:...`) for SBOMs generated by tag with no embedded digest.
//
//     go run ./tools/sbom-submit alpine.cdx.json [repo@sha256:...]
//
// Config via environment:
//
//	DR_TOKEN     API token (required — the tool errors out if unset).
//	DR_BASE_URL  Target service. Defaults to https://devradar.thingz.io.
//
// Image mode shells out to `syft` and `crane` (consistent with the scan job's
// "shell out to pinned binaries, don't import" model — keeps their heavy
// transitive deps out of this module). Both must be on PATH.
package main

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"
)

func main() {
	if len(os.Args) < 2 {
		log.Fatal("usage: sbom-submit <image-ref | sbom-file> [image_ref@sha256:...]")
	}
	token := os.Getenv("DR_TOKEN")
	if token == "" {
		log.Fatal("DR_TOKEN is not set (mint one in the UI, or 'make seed' locally)")
	}
	base := strings.TrimRight(os.Getenv("DR_BASE_URL"), "/")
	if base == "" {
		base = "https://devradar.thingz.io"
	}

	arg := os.Args[1]

	var sbomBytes []byte
	var imageRef, version string

	if fileExists(arg) {
		// File mode: submit an existing SBOM, with an optional image_ref override.
		raw, err := os.ReadFile(arg)
		if err != nil {
			log.Fatalf("read sbom: %v", err)
		}
		sbomBytes = raw
		if len(os.Args) > 2 {
			imageRef = os.Args[2]
		}
	} else {
		// Image mode: resolve digest, generate SBOM, submit.
		requireBinaries("crane", "syft")
		ref, sbom, err := sbomForImage(arg)
		if err != nil {
			log.Fatalf("generate sbom for %s: %v", arg, err)
		}
		sbomBytes = sbom
		imageRef = ref       // digest-pinned ref, so the stored label is unambiguous
		version = tagOf(arg) // preserve the human tag (e.g. v1.20.2) the digest replaced
	}

	if err := submit(base, token, sbomBytes, imageRef, version); err != nil {
		log.Fatal(err)
	}
}

// sbomForImage resolves image's manifest digest and returns the digest-pinned
// reference plus an all-layers CycloneDX SBOM generated against it. Generating
// by digest (not the tag) is what makes the SBOM carry the manifest digest the
// service needs to pin the inventory.
func sbomForImage(image string) (ref string, sbom []byte, err error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	digest, err := run(ctx, "crane", "digest", image)
	if err != nil {
		return "", nil, fmt.Errorf("crane digest: %w", err)
	}
	digest = strings.TrimSpace(digest)

	// Pin to repo@sha256:... — strip any :tag from the input first.
	ref = repoOf(image) + "@" + digest
	log.Printf("resolved %s -> %s", image, ref)

	log.Printf("generating all-layers CycloneDX SBOM (syft)...")
	out, err := run(ctx, "syft", "-q", "--scope", "all-layers", "-o", "cyclonedx-json", ref)
	if err != nil {
		return "", nil, fmt.Errorf("syft: %w", err)
	}
	return ref, []byte(out), nil
}

// repoOf strips a :tag from an image reference, preserving a registry host:port.
// "quay.io/foo/bar:v1" -> "quay.io/foo/bar"; "foo/bar" -> "foo/bar".
func repoOf(image string) string {
	// A tag, if present, is after the last ':' and contains no '/'.
	if i := strings.LastIndex(image, ":"); i != -1 && !strings.Contains(image[i+1:], "/") {
		return image[:i]
	}
	return image
}

// tagOf returns the :tag from an image reference, or "" if none (mirrors repoOf).
func tagOf(image string) string {
	if i := strings.LastIndex(image, ":"); i != -1 && !strings.Contains(image[i+1:], "/") {
		return image[i+1:]
	}
	return ""
}

func submit(base, token string, sbom []byte, imageRef, version string) error {
	payload := map[string]string{"sbom": base64.StdEncoding.EncodeToString(sbom)}
	if imageRef != "" {
		payload["image_ref"] = imageRef
	}
	if version != "" {
		payload["version"] = version
	}
	body, _ := json.Marshal(payload)

	req, err := http.NewRequest(http.MethodPost, base+"/v1/sboms", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("submit: %w", err)
	}
	out, _ := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	fmt.Printf("HTTP %d: %s\n", resp.StatusCode, out)
	if resp.StatusCode >= 300 {
		return fmt.Errorf("submission failed with status %d", resp.StatusCode)
	}
	return nil
}

// run executes a command and returns its stdout, wrapping a failure with stderr.
func run(ctx context.Context, name string, args ...string) (string, error) {
	var stdout, stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("%w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return stdout.String(), nil
}

func requireBinaries(names ...string) {
	for _, n := range names {
		if _, err := exec.LookPath(n); err != nil {
			log.Fatalf("%q not found on PATH (image mode needs syft + crane); "+
				"install it, or pass an existing SBOM file instead", n)
		}
	}
}

func fileExists(p string) bool {
	info, err := os.Stat(p)
	return err == nil && !info.IsDir()
}
